#!/usr/bin/env python3
"""THE VERIFICATION PATH (v3). Verifies an evidence bundle of the auditable skill-installation experiments:
  0. TRUST ROOT  prints the sha256 of this script, README.md, bundle.json and SHA256SUMS so a reader can bind a run to exact files.
  1. HASHES      every file listed in SHA256SUMS matches; every pre-registration sha quoted in bundle.json matches; the inventory (file, arm
                 and prereg counts recorded in bundle.json) is met and nonzero. ANY failure here stops the run before anything executable.
  2. BILLS+BIND  the protected-panel damage bill and sign crossings are recomputed from the saved base and candidate margins (641 facts, the
                 SAME id set on both sides, every margin finite), and every number in the tables is bound to the file it comes from: teach and
                 held-out counts to the cap reports (n_passed == count of passed rows; unique task ids; split field consistent; row count ==
                 n_tasks), HumanEval+ to the scoring receipt (plus_pass; samples sha), bill to the price file.
  3. ANCHORS     (executes model-generated programs through evalplus; skipped by --static-only / --skip-anchors) the saved HumanEval+ samples are
                 rescored with evalplus in a temporary directory and compared to the saved scoring receipts.
  4. SKILLS      (executes model-generated programs with the family graders; OPT-IN with --regrade; each report in its own subprocess with a
                 timeout; not an OS sandbox: run it in a container or VM if you do not trust the bundle) every task of every report that stores
                 the code is re-executed and the pass count compared.
  2b. CODE BIND  where a code-storing re-read exists for an arm first read with code shas only, every stored program is hashed against the
                 first read's recorded code_sha256 (retroactive verification of the hash-only tables).
  2c. LOGPROBS   every margin recomputed from the stored per-candidate log-probabilities and the bank's gold answer; gains recomputed.
  2d. RECEIPTS   each runner receipt's recorded read-file shas bound to the shipped files, its bill to the table, its weights sha to the
                 export manifest and the FP-688 loss receipts that name the same weights.
  4b. LMLOSS     the FP-688 held-out-loss deltas are recomputed from base and candidate receipts (same text sha, token count, torch, gpu).
  5. TABLES      the head-to-head and two-family tables are reprinted from the evidence just verified.
Exit status is nonzero on any mismatch. Usage: python verify.py [--static-only] [--skip-anchors] [--regrade] [--bundle DIR]
  --static-only : steps 0, 1, 2, 4b, 5 only; nothing generated by a model is executed (about one second anywhere, Windows included).
  --regrade     : also run step 4 (the only step that executes model-generated code outside evalplus)."""
import argparse
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
import tempfile
import functools

print = functools.partial(print, flush=True)
sys.dont_write_bytecode = True

HERE = os.path.dirname(os.path.abspath(__file__))


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def load(p):
    return json.load(open(p, encoding="utf-8"))


class V:
    def __init__(self):
        self.fail = 0
        self.n = 0

    def check(self, ok, msg):
        self.n += 1
        print(("  ok   " if ok else "  FAIL ") + msg)
        if not ok:
            self.fail += 1
        return ok


def step_trust_root(root):
    print("[0] trust root")
    for name in ["verify.py", "README.md"]:
        p = os.path.join(HERE, name)
        print("  %s  %s" % (sha(p) if os.path.exists(p) else "MISSING".ljust(64), name))
    for name in ["bundle.json", "SHA256SUMS"]:
        p = os.path.join(root, name)
        print("  %s  evidence/%s" % (sha(p) if os.path.exists(p) else "MISSING".ljust(64), name))


def step_hashes(v, B, root):
    print("[1] hashes and inventory")
    inv = B.get("inventory") or {}
    sums = os.path.join(root, "SHA256SUMS")
    lines = [l.strip() for l in open(sums, encoding="utf-8") if l.strip()]
    v.check(len(lines) > 0 and inv.get("files", -1) == len(lines), "SHA256SUMS lists %d files (inventory says %s)" % (len(lines), inv.get("files")))
    v.check(inv.get("arms", -1) == len(B["arms"]) and len(B["arms"]) > 0, "bundle carries %d arms (inventory says %s)" % (len(B["arms"]), inv.get("arms")))
    v.check(inv.get("preregs", -1) == len(B.get("preregs", [])) and len(B.get("preregs", [])) > 0, "bundle carries %d preregs (inventory says %s)" % (len(B.get("preregs", [])), inv.get("preregs")))
    seen = set()
    for line in lines:
        want, rel = line.split(None, 1)
        rel = rel.lstrip("*")
        seen.add(rel)
        p = os.path.join(root, rel)
        v.check(os.path.exists(p) and sha(p) == want, "%s" % rel)
    v.check("bundle.json" in seen, "bundle.json is itself listed in SHA256SUMS")
    stray = []
    for dp, dns, fns in os.walk(root):
        for fn in fns:
            rel = os.path.relpath(os.path.join(dp, fn), root).replace("\\", "/")
            if rel != "SHA256SUMS" and rel not in seen:
                stray.append(rel)
    v.check(not stray, "no unlisted files in the evidence tree (%d stray: %s)" % (len(stray), ", ".join(stray[:5])))
    for pr in B.get("preregs", []):
        p = os.path.join(root, pr["file"])
        v.check(os.path.exists(p) and sha(p).startswith(pr["sha16"]), "prereg %s frozen sha %s" % (pr["file"], pr["sha16"]))


def bill(base, state):
    mb, ms = base["margins"], state["margins"]
    ids = [i for i in mb if i in ms]
    crossings = [i for i in ids if mb[i] > 0 and ms[i] < 0]
    return sum(max(0.0, mb[i] - ms[i]) for i in ids), len(crossings), len(ids)


def finite(m):
    return all(isinstance(x, (int, float)) and not isinstance(x, bool) and math.isfinite(x) for x in m.values())


def step_bills_and_bind(v, B, root):
    print("[2] panel bills recomputed from saved margins; table numbers bound to their files")
    for arm in B["arms"]:
        name = arm["name"]
        if "panel" in arm and "base_panel" in arm:
            base = load(os.path.join(root, arm["base_panel"]))
            st = load(os.path.join(root, arm["panel"]))
            same_ids = set(base["margins"]) == set(st["margins"])
            ok_fin = finite(base["margins"]) and finite(st["margins"])
            b, c, n = bill(base, st)
            v.check(same_ids and ok_fin and n == 641, "%s panel: 641 ids, identical id set on both sides, all margins finite (n=%d same=%s finite=%s)" % (name, n, same_ids, ok_fin))
            v.check(abs(b - arm["bill"]) < 1e-3 and c == arm["crossings"], "%s bill %.3f crossings %d (recorded %.3f / %d)" % (name, b, c, arm["bill"], arm["crossings"]))
            if "price" in arm:
                pr = load(os.path.join(root, arm["price"]))
                pb, pc = pr.get("damage_bill_nats", pr.get("bill")), pr.get("n_sign_crossings", pr.get("crossings"))
                v.check(pb is not None and abs(pb - b) < 1e-3 and pc == c, "%s price file agrees (%.3f / %s)" % (name, pb if pb is not None else float("nan"), pc))
        for rep in arm.get("cap_reports", []):
            r = load(os.path.join(root, rep["file"]))
            rows = r["rows"]
            ids = [row["task_id"] for row in rows]
            npass = sum(1 for row in rows if row.get("passed") is True)
            ok = (len(ids) == len(set(ids)) == r["n_tasks"] and all(row.get("split") == r["split"] == rep["split"] for row in rows) and npass == r["n_passed"])
            key = "teach" if rep["split"] == "teach" else "heldout"
            key = key + ("_quill" if rep["family"] == "quill" else "")
            bound = arm.get(key) is None or arm.get(key) == r["n_passed"]
            v.check(ok and bound, "%s %s %s report: %d unique rows, %d passed == n_passed %d, table %s=%s" % (name, rep["family"], rep["split"], len(ids), npass, r["n_passed"], key, arm.get(key)))
        if "samples" in arm:
            sr = load(os.path.join(root, arm["anchor_files"]["scoring_receipt"])) if arm.get("anchor_files", {}).get("scoring_receipt") else None
            sp = os.path.join(root, arm["samples"])
            ok = sr is not None and sr.get("plus_pass") == arm.get("plus") and sha(sp) == arm["samples_sha256"] and (sr.get("samples_sha256") in (None, sha(sp)))
            v.check(ok, "%s HumanEval+ %s bound to scoring receipt (plus_pass %s; samples sha %s)" % (name, arm.get("plus"), sr.get("plus_pass") if sr else None, arm["samples_sha256"][:16]))


def step_code_binding(v, B, root):
    """Where a code-storing re-read exists for an arm that was first read with code shas only, bind them: sha256 of every stored program must
    equal the first read's recorded code_sha256 for the same task. 100 percent means the first table's teach column is retroactively verified
    from the second's stored code; less means the two reads did not generate the same programs (reported, not failed, unless the bundle marks
    the pair as expected-identical)."""
    pairs = B.get("code_bindings") or []
    if not pairs:
        return
    print("[2b] stored code of re-reads bound to the first reads' code shas")
    byname = {a["name"]: a for a in B["arms"]}
    for pb in pairs:
        a1, a2 = byname.get(pb["first"]), byname.get(pb["second"])
        if not a1 or not a2:
            v.check(False, "code binding %s <-> %s: arm missing" % (pb["first"], pb["second"])); continue
        tot = same = 0
        for r1, r2 in zip(a1.get("cap_reports", []), a2.get("cap_reports", [])):
            if (r1["family"], r1["split"]) != (r2["family"], r2["split"]):
                continue
            rows1 = {row["task_id"]: row for row in load(os.path.join(root, r1["file"]))["rows"]}
            for row in load(os.path.join(root, r2["file"]))["rows"]:
                if "code" not in row or row["task_id"] not in rows1:
                    continue
                tot += 1
                if hashlib.sha256(row["code"].encode("utf-8")).hexdigest() == rows1[row["task_id"]].get("code_sha256"):
                    same += 1
        ok = (same == tot) if pb.get("expect_identical") else True
        v.check(ok and tot > 0, "%s <-> %s: %d / %d stored programs hash to the first read's code shas%s" % (pb["first"], pb["second"], same, tot, " (expected identical)" if pb.get("expect_identical") else ""))


def step_anchors(v, B, root, skip):
    print("[3] HumanEval+ samples rescored with evalplus" + (" (skipped)" if skip else " (executes model-generated programs via evalplus)"))
    if skip:
        return
    try:
        import evalplus  # noqa: F401
    except Exception:
        v.check(False, "evalplus not importable (pip install evalplus==0.3.1; run on Linux / macOS / WSL)")
        return
    scored = {}
    for arm in B["arms"]:
        if "samples" not in arm:
            continue
        sp = os.path.join(root, arm["samples"])
        v.check(sha(sp) == arm["samples_sha256"], "%s samples sha %s" % (arm["name"], arm["samples_sha256"][:16]))
        if arm["samples_sha256"] in scored:
            v.check(scored[arm["samples_sha256"]] == arm["plus"], "%s plus %d (recorded %d; same bytes as an already rescored file)" % (arm["name"], scored[arm["samples_sha256"]], arm["plus"]))
            continue
        tmp = tempfile.mkdtemp(prefix="auditkit_")
        sp2 = os.path.join(tmp, os.path.basename(sp))
        shutil.copyfile(sp, sp2)
        res = subprocess.run([sys.executable, "-m", "evalplus.evaluate", "--dataset", "humaneval", "--samples", sp2], capture_output=True, text=True)
        out = sp2.replace(".jsonl", "_eval_results.json")
        if not os.path.exists(out):
            v.check(False, "%s evalplus produced no results (%s)" % (arm["name"], res.stderr[-200:]))
            shutil.rmtree(tmp, ignore_errors=True)
            continue
        ev = load(out)["eval"]
        plus = sum(1 for x in ev.values() if x[0]["base_status"] == "pass" and x[0]["plus_status"] == "pass")
        scored[arm["samples_sha256"]] = plus
        v.check(plus == arm["plus"], "%s plus %d (recorded %d)" % (arm["name"], plus, arm["plus"]))
        shutil.rmtree(tmp, ignore_errors=True)


REGRADE_RUNNER = r'''
import json, sys, importlib
root, fam_dir, rep_file = sys.argv[1], sys.argv[2], sys.argv[3]
sys.path.insert(0, fam_dir)
r = json.load(open(rep_file, encoding="utf-8"))
family = r["family_module"].replace("_tasks", "")
FT = importlib.import_module("%s_tasks" % family)
fam = json.load(open("%s/%s_family.json" % (fam_dir, family), encoding="utf-8"))
by = {t["task_id"]: t for t in fam[r["split"]]}
n = sum(1 for row in r["rows"] if bool(FT.grade(row["code"], by[row["task_id"]])[0]))
print("REGRADED %d" % n)
'''


def step_skills(v, B, root, enabled):
    print("[4] skill generations re-executed with the family graders" + ("" if enabled else " (opt-in: pass --regrade; this step executes model-generated code)"))
    if not enabled:
        return
    fam_dir = os.path.join(root, "families")
    for arm in B["arms"]:
        for rep in arm.get("cap_reports", []):
            rf = os.path.join(root, rep["file"])
            r = load(rf)
            if not r["rows"] or "code" not in r["rows"][0]:
                print("  skip %s %s %s: code not stored in this report (hashes only)" % (arm["name"], rep["family"], rep["split"]))
                continue
            try:
                env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
                res = subprocess.run([sys.executable, "-B", "-c", REGRADE_RUNNER, root, fam_dir, rf], capture_output=True, text=True, timeout=900, cwd=tempfile.mkdtemp(prefix="auditkit_regrade_"), env=env)
                m = [l for l in res.stdout.splitlines() if l.startswith("REGRADED ")]
                n = int(m[-1].split()[1]) if m else None
            except subprocess.TimeoutExpired:
                n = None
            v.check(n == r["n_passed"], "%s %s %s regraded %s (recorded %d)" % (arm["name"], rep["family"], r["split"], n, r["n_passed"]))


def step_margins_from_logprobs(v, B, root):
    """Every panel read stores the per-candidate log-probabilities; the bank stores the gold answer. Recompute every margin (gold minus the
    best rival) from those and compare to the stored margin; also recompute the gain column. Catches a bill forged consistently across the
    margins, bundle.json and the price file (a fully re-signed forgery) unless the forger also rewrites the raw log-probabilities."""
    print("[2c] margins recomputed from raw log-probabilities and the bank's answers; gains recomputed")
    bank = {it["id"]: it for it in load(os.path.join(root, "panel", "fp454_bank.json"))["items"]}
    seen = set()
    for arm in B["arms"]:
        for key in ("panel", "base_panel"):
            rel = arm.get(key)
            if not rel or rel in seen:
                continue
            seen.add(rel)
            P = load(os.path.join(root, rel))
            lp, mg = P.get("logprobs") or {}, P["margins"]
            n = bad = missing = 0
            for i, m in mg.items():
                if i not in lp or i not in bank:
                    missing += 1; continue
                ans = bank[i]["answer"]
                if ans not in lp[i]:
                    missing += 1; continue
                gold = lp[i][ans]
                rivals = [val for k, val in lp[i].items() if k != ans]
                if not rivals:
                    missing += 1; continue
                n += 1
                if abs((gold - max(rivals)) - m) > 1e-4:
                    bad += 1
            v.check(n == len(mg) and bad == 0 and missing == 0, "%s: %d / %d margins recomputed from log-probabilities (%d mismatched, %d unrecomputable)" % (rel, n - bad, len(mg), bad, missing))
        if "gain" in arm and "panel" in arm and "base_panel" in arm:
            mb, ms = load(os.path.join(root, arm["base_panel"]))["margins"], load(os.path.join(root, arm["panel"]))["margins"]
            g = sum(max(0.0, ms[i] - mb[i]) for i in mb if i in ms)
            v.check(abs(g - arm["gain"]) < 1e-3, "%s gain %.3f (recorded %.3f)" % (arm["name"], g, arm["gain"]))


def step_receipt_chain(v, B, root):
    """Bind each arm's runner receipt to the files the kit ships: the receipt's recorded shas of its own reads (samples, panel, cap reports,
    price, base panel) must equal the sha of the shipped file, its bill must equal the table, and its weights sha must equal every other
    place that names those weights (the FP-688 loss receipt, the export manifest where shipped). This is the chain samples -> receipt -> weights;
    the kit still cannot re-derive a number from weights, but a swapped file now has to be swapped in every file that names it."""
    print("[2d] receipt chain: read-file shas, bill, and weights sha bound across receipts, manifests and loss receipts")
    lm_by_model = {}
    for sha16, rel in (B.get("lmloss", {}).get("receipts") or {}).items():
        r = load(os.path.join(root, rel))
        if r.get("model_safetensors_sha256"):
            lm_by_model.setdefault(r["model_safetensors_sha256"], []).append(r["tag"])
    for arm in B["arms"]:
        rel = arm.get("receipt")
        if not rel:
            continue
        r = load(os.path.join(root, rel))
        reads = r.get("reads")
        if not reads:
            print("  info %s: writer receipt only (no reads block); weights binding via manifest only" % arm["name"])
        else:
            pairs = [("anchor_samples_sha256", arm.get("samples")), ("panel_read_sha256", arm.get("panel")), ("base_panel_sha256", arm.get("base_panel")), ("price_sha256", arm.get("price"))]
            for rep in arm.get("cap_reports", []):
                k = ("teach_report_sha256" if rep["split"] == "teach" else "heldout_report_sha256") if rep["family"] == "vex" else ("quill_teach_report_sha256" if rep["split"] == "teach" else "quill_heldout_report_sha256")
                pairs.append((k, rep["file"]))
            n = ok = 0
            for k, f in pairs:
                if k in reads and f:
                    n += 1
                    ok += int(sha(os.path.join(root, f)) == reads[k])
            billok = ("bill" not in arm) or (reads.get("bill") is None) or abs(float(reads["bill"]) - arm["bill"]) < 1e-3
            v.check(n > 0 and ok == n and billok, "%s receipt: %d / %d recorded read-file shas match the shipped files; receipt bill == table: %s" % (arm["name"], ok, n, billok))
        msha = r.get("model_safetensors_sha256")
        man = None
        for cand in ("A_written_bf16/MANIFEST-SHA256.json", "MANIFEST-SHA256.json"):
            mp = os.path.join(root, os.path.dirname(rel), cand)
            if os.path.exists(mp):
                man = load(mp).get("files_sha256", {}).get("model.safetensors"); break
        if msha or man:
            agree = [x for x in (msha, man) if x]
            same = len(set(agree)) == 1
            tags = lm_by_model.get(agree[0], []) if agree else []
            v.check(same, "%s weights sha %s: receipt/manifest agree (%s); named by FP-688 receipts: %s" % (arm["name"], (agree[0] if agree else "-")[:16], same, ",".join(tags) or "-"))


def step_lmloss(v, B, root):
    if "lmloss" not in B:
        return
    print("[4b] FP-688 held-out language-modelling loss: deltas recomputed from receipts")
    for sha16, rel in sorted(B["lmloss"]["receipts"].items()):
        r = load(os.path.join(root, rel))
        pd = [x for x in r["per_doc_nll"] if x is not None]
        v.check(len(pd) == r["n_docs"] == 200 and r["tokens_scored"] > 0 and math.isfinite(r["mean_nll_nats"]), "%s receipt: %d docs scored, %d tokens, mean NLL %.5f nats" % (r["tag"], len(pd), r["tokens_scored"], r["mean_nll_nats"]))
    for name, row in B["lmloss"]["rows"].items():
        if not row.get("receipt") or not row.get("base_receipt"):
            v.check(False, "%s receipt missing from bundle" % name); continue
        c, b = load(os.path.join(root, row["receipt"])), load(os.path.join(root, row["base_receipt"]))
        same = c["text_sha256"] == b["text_sha256"] and c["tokens_scored"] == b["tokens_scored"] and c["stack"]["torch"] == b["stack"]["torch"] and c["stack"]["gpu"] == b["stack"]["gpu"]
        d = c["mean_nll_nats"] - b["mean_nll_nats"]
        v.check(same and abs(d - row["dnll"]) < 1e-5, "%s dNLL %+.5f nats (recorded %+.5f) vs %s [%s]; same text, tokens, torch, gpu: %s" % (name, d, row["dnll"], b["tag"], b["stack"]["gpu"], same))
        pc, pb = c["per_doc_nll"], b["per_doc_nll"]
        pairs = [(x, y) for x, y in zip(pc, pb) if x is not None and y is not None]
        dd = [x - y for x, y in pairs]
        ud = sum(dd) / len(dd)
        worse = sum(1 for z in dd if z > 0)
        v.check(len(pairs) == 200 and abs(ud - d) < 0.01 and (ud > 0) == (d > 0), "%s per-document deltas: unweighted mean %+.5f (token-weighted %+.5f), candidate worse on %d / %d documents" % (name, ud, d, worse, len(pairs)))


def step_tables(B):
    print("[5] tables from verified evidence")
    for tname, arms in B["tables"].items():
        print("  " + tname)
        print("  %-22s %8s %8s %8s %8s %8s %10s %5s %10s" % ("arm", "vex/60", "vex-ho", "quill/60", "quill-ho", "plus/164", "bill(nats)", "cross", "gain(nats)"))
        for a in arms:
            arm = next(x for x in B["arms"] if x["name"] == a)
            g = lambda k: "-" if arm.get(k) is None else arm.get(k)
            print("  %-22s %8s %8s %8s %8s %8s %10s %5s %10s" % (a, g("teach"), g("heldout"), g("teach_quill"), g("heldout_quill"), g("plus"), ("%.1f" % arm["bill"]) if "bill" in arm else "-", g("crossings"), ("%.1f" % arm["gain"]) if "gain" in arm else "-"))
        print("  bill = summed margin LOSS over the 641 facts (one-sided); gain = summed margin gain elsewhere; the screen is on the bill and the crossings.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", default=os.path.join(HERE, "evidence"))
    ap.add_argument("--static-only", action="store_true", help="hashes, bills, bindings, FP-688 arithmetic and tables only; executes nothing generated by a model")
    ap.add_argument("--skip-anchors", action="store_true", help="skip the evalplus rescoring (step 3)")
    ap.add_argument("--regrade", action="store_true", help="also re-execute stored skill generations with the family graders (step 4)")
    a = ap.parse_args()
    root = a.bundle
    B = load(os.path.join(root, "bundle.json"))
    v = V()
    print("audit-kit verify v3.2: %s (%s)" % (B["title"], B["generated"]))
    step_trust_root(root)
    step_hashes(v, B, root)
    if v.fail:
        print("STOP: %d hash / inventory failures; nothing executable was run" % v.fail)
        print("%d checks, %d failures" % (v.n, v.fail))
        sys.exit(1)
    step_bills_and_bind(v, B, root)
    step_code_binding(v, B, root)
    step_margins_from_logprobs(v, B, root)
    step_receipt_chain(v, B, root)
    step_anchors(v, B, root, a.skip_anchors or a.static_only)
    step_skills(v, B, root, a.regrade and not a.static_only)
    step_lmloss(v, B, root)
    step_tables(B)
    print("%d checks, %d failures" % (v.n, v.fail))
    sys.exit(1 if v.fail else 0)


if __name__ == "__main__":
    main()
